MI-1415: Adding Celery functionality
unhaggle/django-mass-edit pull request #4
Opened 2022-10-28 20:30 UTC by Xyloxy

2022-11-21 22:36 UTC, ericrommel requested changes
I think there is something strange here. It worked when I selected only `Title French` for more than 1 object. When I selected the `Title English`, `Title French` and `Dealership`, those fields were changed only to one object (picture below). I can show you it in a call if you didn't understand.

![image](https://user-images.githubusercontent.com/10250819/203172238-f3cd9d2a-1bbc-445a-9394-dadf5114f73f.png)

2022-11-21 22:36 UTC, ericrommel commented on massadmin/massadmin_async.py
> +        # TODO It's necessary to check permission and existence for all object
what will be done later here as you put `TODO`?

2022-11-21 22:36 UTC, ericrommel commented on massadmin/massadmin_async.py
> +                objects = queryset.filter(pk__in=comma_separated_object_ids.split(','))
Have you checked this estimation with our DBA, Imran Hashmi or Robert Szabo, as well? Maybe they can give more advice here.

2022-11-21 22:36 UTC, ericrommel commented on massadmin/tasks.py
> +    # It is a simple query but the impact might be big
Same as my comment before, check with our DBAs

2022-11-21 22:36 UTC, ericrommel commented on tests/urls.py
>      path('admin/', include(massadmin_urls)),
duplicated line?

2022-11-22 10:02 UTC, Xyloxy commented on massadmin/massadmin_async.py
> +        # TODO It's necessary to check permission and existence for all object
It is todo left from original code, I was replacing code step by step with my functionality, so some of it is still there, but this should be deleted

2022-11-22 10:16 UTC, Xyloxy commented
> I think there is something strange here. It worked when I selected only `Title French` for more than 1 object. When I selected the `Title English`, `Title French` and `Dealership`, those fields were changed only to one object (picture below). I can show you it in a call if you didn't understand.
> 
> ![image](https://user-images.githubusercontent.com/10250819/203172238-f3cd9d2a-1bbc-445a-9394-dadf5114f73f.png)

I think I know what is happening here, it is mostly because only 1 object is changed in the main code, only after this more objects are being changed. There must have been an error between those two points

2022-11-25 20:50 UTC, ericrommel commented
I think it is still strange. Also, I couldn't see disabled fields yet (those that can't be changed in bulk mode).

![image](https://user-images.githubusercontent.com/10250819/204054100-78327129-8143-4b95-aca2-3bcf4bed85cb.png)

2022-11-25 21:32 UTC, ericrommel approved these changes
LGTM. The only thing is about Codecov notifications. If we can survive without that, that's fine to me.

2022-11-29 10:02 UTC, danialmalik requested changes
A few general things:
- Instead of copying everything into `massadmin_improved.py`, we don't we just extend the existing one? or to keep new changes separate, make a new class, inherit the old one to re-use all the code without copying anything and just add this new `async` method in the new class. Copying the existing code at two places will make it confusing and hard to maintain. (also more effort into reviewing)
- (probably for future if it's urgently required). We should add some kind of mechanism to choose b/w sync and async methods. probably some kind of django setting backed by `django-constance`.
- Please add docstrings for new methods.

2022-11-29 10:02 UTC, danialmalik commented on massadmin/urls.py
> +    ),
Just some thought: Since we have separate URL for async, how about we keep both options usable, async and sync.
we could add a new admin action for async operation.

2022-11-29 10:02 UTC, danialmalik commented on tests/tests.py
> +    """
```suggestion
    """ImprovedMassAdmin has all customized options from related ModelAdmin"""
```
and at other places.

2022-11-29 10:17 UTC, Xyloxy commented on massadmin/massadmin_improved.py
> +        # Only one form needs to be validated, as the same fields are being used
That's the reason why we're using atomic during save.

I cannot catch all errors, mostly because not always all fields are present in the form, making it impossible to test, as the form just doesn't know what the other fields are. That's the reason we moved away from the original concept of doing all the tests and sending verified data to celery, as even though we were going through all objects, it's actually only checking for the changed field.

During saving in line 174, Django does it's own constraint checks before saving to the database. So even though we might have passed the tests done in validate_form, it is just supposed to check for the user error. The more complex relation constraints are being checked just before saving. (If any errors show up during atomic transaction, the transaction is being reverted and an error is being pushed with information what has happened on top of the page)

So far this has been the only reliable way of doing this without the amount of work that has been present in original `mass-django-edit`, with full proper validation, but if you have any suggestions please follow up with a message.

2022-11-29 10:25 UTC, Xyloxy commented on massadmin/urls.py
> +    ),
That was my concept, but it would require a lot of work on tier3 side, as literally only one admin object inherits django-mass-admin, so we'd have to go one by one in every Admin to add that. I just keep that in for easy way or reverting the changes

2022-11-29 11:04 UTC, Xyloxy commented on massadmin/massadmin_improved.py
> +        # Only one form needs to be validated, as the same fields are being used
> A few general things:
> 
>     * Instead of copying everything into `massadmin_improved.py`, we don't we just extend the existing one? or to keep new changes separate, make a new class, inherit the old one to re-use all the code without copying anything and just add this new `async` method in the new class. Copying the existing code at two places will make it confusing and hard to maintain. (also more effort into reviewing)
> 
>     * (probably for future if it's urgently required). We should add some kind of mechanism to choose b/w sync and async methods. probably some kind of django setting backed by `django-constance`.
> 
>     * Please add docstrings for new methods.

1. That's what I did, I imported most of what I could into the async from original, sadly not all functions are redundant in that case, and some have just a word of difference, but otherwise it won't work.
2. Maybe, yes, I do not know, noone proposed that before, but I think this would be a 2nd thought and in another ticket
3. On my way

2022-11-29 11:38 UTC, Xyloxy commented on massadmin/urls.py
> +    ),
This prevents errors in case when some other part of the application uses the mass-edit too

2022-11-30 10:37 UTC, danialmalik commented on massadmin/massadmin_improved.py
> +        # Only one form needs to be validated, as the same fields are being used
I still think we should have updated the existing code. We could split the big methods with minor changes into smaller methods and change the method we needed to.
or just add new methods for different functionality. this way, there is no use to keep the existing `MassAdmin` class.

2022-11-30 10:55 UTC, danialmalik commented
When I tried to test it (on squash and locally as it's easier to switch between branches and versions locally), i did the same test I mentioned earlier: to test updating the dealerships' trade in system variant with different trade in systems.

In this PR version, I get only this generic error: 
![image](https://user-images.githubusercontent.com/42166091/204777489-b64623a6-da7f-41e4-97af-a83c174c5982.png)
with no error on the field:
![image](https://user-images.githubusercontent.com/42166091/204777540-1f527ffb-c19b-46e5-bbd0-dd1ee9363edd.png)

also, there is no email.

but in the current version, i repeat the same errors and get this error:
![image](https://user-images.githubusercontent.com/42166091/204777925-f558f3c4-1484-491d-a451-5b4c14dd0c80.png)


with the error on actual field as well:
![image](https://user-images.githubusercontent.com/42166091/204777985-edc3415b-957d-40ad-b326-d56c78cf118e.png)


so in this updated version, I have no way of knowing what I am doing wrong while doing the bulk edit. This is a potential issue which should be fixed.

2022-11-30 13:30 UTC, Xyloxy commented
> , I have no way of knowing what

@danialmalik 
I've pushed change that I overlooked, now user is getting information on what is wrong.

2022-11-30 13:46 UTC, Xyloxy commented
> > , I have no way of knowing what
> 
> @danialmalik I've pushed change that I overlooked, now user is getting information on what is wrong.

In `mass-django-edit` form errors under the fields are not supported yet, but we can add it in another ticket further down the line

2022-12-07 18:22 UTC, Xyloxy commented on massadmin/massadmin_improved.py
> +        # Only one form needs to be validated, as the same fields are being used
I think we should keep it just in cause of major updates to the original branch or some other stuff happening that's out of our control. It will make it so if needed we can turn it back on for specific Admins in case of some obscure functionality being needed.

2022-12-12 11:14 UTC, danialmalik reviewed
Overall this looks fine to me, with some suggestions.

My thoughts are just:
- We are relying on django's `update` to do the validations. There are many validations in Django Forms and not on models so we miss that.
- `massadmin` itself only sends the "changed" data to backend. and if the changed data is same for all edited objects, it is fine to validate only one object. so there is no downgrade here potentially.
- But this statement above only applies for django form validations relying only on `form data`. In validations where form data is validated in combination with the object's properties, different objects may result differently on validations even if the updated fields have same values. This is where the new implementation fails while the current one passes. Consider this scenario:
    - There are two objects A and B. and there is a validation like `if form_data["prop_a"] == obj.prop_b: raise Exception`. When we massedit the two objects, and current implementation of `massadmin` applies validation on both of these objects one by one, it passes for object A but fails for object B (due to object B's `prop_b` attribute).  In the new implementation, when we do form validation on only first object, it will pass and will update the second object too whereas it shouldn't have as per the current implementation. 
        I am not even sure if we have such validations or how many, but still it is something that we should consider and make our decision if we can ignore this scenario.

2022-12-12 21:09 UTC, Xyloxy commented on massadmin/massadmin_improved.py
> +def async_mass_change_view(request, app_name, model_name, object_ids, admin_site=None):
Yes, the async should be renamed to default name

2022-12-12 21:16 UTC, Xyloxy commented on massadmin/massadmin_improved.py
> +def mass_change_selected(modeladmin, request, queryset):
Hey, this function just has the same name as the one in `massadmin.py` but has other code inside, should we rename it?

2022-12-13 07:29 UTC, danialmalik commented on massadmin/massadmin_improved.py
> +def mass_change_selected(modeladmin, request, queryset):
:thinking: I did a "find" on the code from `massadmin.py` in `massadmin_improved.py` and found the exact match. Where is the difference? :thinking: 
![image](https://user-images.githubusercontent.com/42166091/207253144-ba58ca6b-b6b8-4497-bde6-0fbd85d77c0b.png)

2022-12-13 09:54 UTC, Xyloxy commented on massadmin/massadmin_improved.py
> +def mass_change_selected(modeladmin, request, queryset):
Yes, but it utilizes different functions inside of it, the `mass_change_selected` in `massadmin.py` uses `get_mass_change_redirect_url` from `massadmin.py` and `mass_change_selected` in `massadmin_improved.py` uses `get_mass_change_redirect_url` from `massadmin_improved.py`

2023-01-11 08:35 UTC, danialmalik reviewed
Just some very minor comments. Otherwise looks fine to me.
Need to do the testing now so not approving yet.

2023-01-11 08:35 UTC, danialmalik commented on massadmin/massadmin_improved.py
> +class MassAdmin(massadmin.MassAdmin):
Change the name so  that it doesn't conflict with the original one? like `MassAdminV2` ?

2023-01-18 02:45 UTC, mbarakaja approved these changes
Works as described.

2023-01-18 09:14 UTC, danialmalik approved these changes

2023-01-19 11:56 UTC, merged